export const myInspos = [
{"id":"1","description":"You shall remember this victory forever.","category":"Heartening","recipient":"Others","source":""},
{"id":"2","description":"One day, your grandchildren shall tell the tale of this moment.","category":"Heartening","recipient":"Others","source":""},
{"id":"3","description":"You know your worth. It's time to show it.","category":"Heartening","recipient":"Others","source":""},
{"id":"4","description":"Your success shall be all our success.","category":"Heartening","recipient":"Others","source":""},
{"id":"5","description":"We are relying on you. You must believe you can do this.","category":"Heartening","recipient":"Others","source":""},
{"id":"6","description":"Once, I made the decision to stand by your side, and I make that same choice again now.","category":"Heartening","recipient":"Others","source":""},
{"id":"7","description":"You were born for greatness.","category":"Heartening","recipient":"Others","source":""},
{"id":"8","description":"Cast aside all your doubts, my friend.","category":"Heartening","recipient":"Others","source":""},
{"id":"9","description":"There is no greater companion than you.","category":"Heartening","recipient":"Others","source":""},
{"id":"10","description":"I am with you, from now until the end.","category":"Heartening","recipient":"Others","source":""},
{"id":"11","description":"You have a gift unlike any other. I am proud to be your companion.","category":"Heartening","recipient":"Others","source":""},
{"id":"12","description":"I have never been more certain about what must be done now.","category":"Heartening","recipient":"Others","source":""},
{"id":"13","description":"I believe in you, not because you are infallible, but because you never give up.","category":"Heartening","recipient":"Others","source":""},
{"id":"14","description":"Everyone else is watching you, doubting you. That is why they will not succeed, and you will.","category":"Heartening","recipient":"Others","source":""},
{"id":"15","description":"The sweetness of victory shall be like divine honey. Can you already taste it?","category":"Heartening","recipient":"Others","source":""},
{"id":"16","description":"Let them cower before our fury!","category":"Bold","recipient":"Others","source":""},
{"id":"17","description":"Let them taste our might!","category":"Bold","recipient":"Others","source":""},
{"id":"18","description":"Your strength is a dragon's roar!","category":"Bold","recipient":"Others","source":""},
{"id":"19","description":"Our foes are gnawing vermin! Scatter them before you!","category":"Bold","recipient":"Others","source":""},
{"id":"20","description":"Summon your courage from deep within!","category":"Bold","recipient":"Others","source":""},
{"id":"21","description":"No wall is too high, no sea too vast! You are as hurricane gale!","category":"Bold","recipient":"Others","source":""},
{"id":"22","description":"The fire burning within you is as great as a thousand suns!","category":"Bold","recipient":"Others","source":""},
{"id":"23","description":"Even the gods shall be awestruck by your deeds!","category":"Bold","recipient":"Others","source":""},
{"id":"24","description":"Hesitate not, my comrade! Onward!","category":"Bold","recipient":"Others","source":""},
{"id":"25","description":"This is the moment we change the course of history!","category":"Bold","recipient":"Others","source":""},
{"id":"26","description":"Look Death in the eye and tell him, 'Not today!'","category":"Bold","recipient":"Others","source":""},
{"id":"27","description":"The heart of a lion beats within your chest!","category":"Bold","recipient":"Others","source":""},
{"id":"28","description":"Do not listen to the critics and complainers! You are the one reaching ever closer to glory!","category":"Bold","recipient":"Others","source":""},
{"id":"29","description":"Let your passion set the world on fire!","category":"Bold","recipient":"Others","source":""},
{"id":"30","description":"Give up and die, or fight and live!","category":"Bold","recipient":"Others","source":""},
{"id":"31","description":"The darkness is full of everything you fear, yet everything you seek!","category":"Bold","recipient":"Others","source":""},
{"id":"32","description":"Do you fear this monster? You should. But even more, it should fear you!","category":"Bold","recipient":"Others","source":""},
{"id":"33","description":"Strike them down. We may not be in the right, but I don't care. In battle, it doesn't matter who's right, it matters who's left.","category":"Humorous","recipient":"Others","source":""},
{"id":"34","description":"By the end of this, we just might have to eat a bucket of worms. Well, better that than be eaten by worms.","category":"Humorous","recipient":"Others","source":""},
{"id":"35","description":"This might end in disaster. But it also might end in us becoming the richest bastards in the world.","category":"Humorous","recipient":"Others","source":""},
{"id":"36","description":"In goblin cities, they don't throw out their garbage. They turn it into more goblins. Let's clean this place up. (or substitute 'goblin' for other monster/race)","category":"Humorous","recipient":"Others","source":""},
{"id":"37","description":"Worry not, when I tell the tale of this moment one day, I'll leave out how you would have failed spectacularly without my help.","category":"Humorous","recipient":"Others","source":""},
{"id":"38","description":"They say it's better to light a candle than curse the darkness. I say it's better to light your foe on fire and let him do the cursing.","category":"Humorous","recipient":"Others","source":""},
{"id":"39","description":"If the monster eats you whole, take solace in knowing it will most likely die trying to shit your sword.","category":"Humorous","recipient":"Others","source":""},
{"id":"40","description":"You're always dressed to kill. You use magic the same way too.","category":"Humorous","recipient":"Others","source":""},
{"id":"41","description":"There is no sweeter music than the screams of our enemies. Now, go compose.","category":"Humorous","recipient":"Others","source":""},
{"id":"42","description":"As much as I would enjoy looting your dead body, I truly do want you to succeed here.","category":"Humorous","recipient":"Others","source":""},
{"id":"43","description":"If reckless shenanigans got us into this mess, then why can't they get us out?","category":"Humorous","recipient":"Others","source":""},
{"id":"44","description":"If it weren't for foolish attempts at glory, then nothing would ever be accomplished.","category":"Humorous","recipient":"Others","source":""},
{"id":"45","description":"You might fail, die even. But at least it won't be boring.","category":"Humorous","recipient":"Others","source":""},
{"id":"46","description":"Just know, when you truly want success, you'll never give up on it. No matter how bad the situation may get.","category":"Heartening","recipient":"Others","source":""},
{"id":"47","description":"Accept responsibility for your life. Know that it is you who will get you where you want to go, no one else.","category":"Heartening","recipient":"Others","source":""},
{"id":"48","description":"I don't regret the things I've done, I regret the things I didn't do when I had the chance.","category":"Heartening","recipient":"Self","source":""},
{"id":"49","description":"Challenges are what make life interesting and overcoming them is what makes life meaningful.","category":"Heartening","recipient":"Others","source":""},
{"id":"50","description":"Good things come to those who wait, greater things come to those who get off their ass and do anything to make it happen.","category":"Heartening","recipient":"Others","source":""},
{"id":"51","description":"In order to succeed, your desire for success should be greater than your fear of failure.","category":"Heartening","recipient":"Others","source":""},
{"id":"52","description":"The best revenge is massive success.","category":"Heartening","recipient":"Others","source":""},
{"id":"53","description":"Don't worry about failures, worry about the chances you miss when you don't even try.","category":"Heartening","recipient":"Others","source":""},
{"id":"54","description":"The pain you feel today is the strength you feel tomorrow. For every challenge encountered there is opportunity for growth.","category":"Heartening","recipient":"Others","source":""},
{"id":"55","description":"Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.","category":"Heartening","recipient":"Others","source":""},
{"id":"56","description":"Life has two rules: #1 Never quit #2 Always remember rule # 1.","category":"Bold","recipient":"Others","source":""},
{"id":"57","description":"Do not wait to strike till the iron is hot; but make it hot by striking.","category":"Bold","recipient":"Others","source":"William B. Sprague"},
{"id":"58","description":"In this life, to earn you place you must fight for it!","category":"Bold","recipient":"Others","source":""},
{"id":"59","description":"In war there is but one favorable moment; the great art is to seize it!","category":"Bold","recipient":"Others","source":"Napoleon Bonaparte"},
{"id":"60","description":"Fight on, brave knights! Man dies, but glory lives! Fight on; death is better than defeat! Fight on brave knights! for bright eyes behold your deeds!","category":"Bold","recipient":"Others","source":"Walter Scott"},
{"id":"61","description":"Where the battle rages, there the measure of the man is proved!","category":"Bold","recipient":"Others","source":"Martin Luther"},
{"id":"62","description":"It is not big armies that win battles, it is the good ones! (replace with \"warriors\")","category":"Bold","recipient":"Others","source":"Marshal Maurice de Saxe (\"Mes Reveries\")"},
{"id":"63","description":"Its not the size of the dog in the fight, but the size of the fight in the dog","category":"Bold","recipient":"Others","source":""},
{"id":"64","description":"A bold warrior may be lucky, but no warrior can be lucky unless he is bold.","category":"Bold","recipient":"Others","source":"Archibald Percival Wavell, Field Marshal"},
{"id":"65","description":"Winners know when to quit. WHEN THEY WIN","category":"Humorous","recipient":"Others","source":""},
{"id":"66","description":"Remember the last guy who quit? EXACTLY. YOU DON'T.","category":"Humorous","recipient":"Others","source":""},
{"id":"67","description":"When there is no peril in the fight there is no glory in the triumph.","category":"Bold","recipient":"Others","source":"Pierre Corneille"},
{"id":"68","description":"Life is tough. BE TOUGHER","category":"Humorous","recipient":"Others","source":""},
{"id":"69","description":"Cowards die many times before their deaths; the valiant never taste death but once.","category":"Bold","recipient":"Others","source":"William Shakespeare (\"Julius Caesar\")"},
{"id":"70","description":"Victory is always possible for the person who refuses to stop fighting.","category":"Bold","recipient":"Others","source":"Napoleon Hill"},
{"id":"71","description":"Courage, above all things, is the first quality of a warrior.","category":"Heartening","recipient":"Others","source":"Carl von Clausewitz"},
{"id":"72","description":"I know what I'm capable of; I am a soldier now, a warrior. I am someone to fear, not hunt.","category":"Heartening","recipient":"Self","source":"Pittacus Lore (\"The Rise of Nine\")"},
{"id":"73","description":"These things we do that others may live.","category":"Heartening","recipient":"Others","source":"USAF Pararescue"},
{"id":"74","description":"When cities burn and armies turn and flee in disarray, cowards will cry: 'Tis best to fly, and fight another day'. But warriors know in their marrow, When they die and fall, 'tis best to have fought and lost than not to have fought at all.'","category":"Heartening","recipient":"Others","source":""},
{"id":"75","description":"If a man hasn't discovered something that he will die for, he isn't fit to live.","category":"Heartening","recipient":"Others","source":"Martin Luther King, Jr"},
{"id":"76","description":"You can never have too many knives, his father had told him. Unless they're pointed at you, and by people who don't like you much.","category":"Humorous","recipient":"Others","source":"Joe Abercrombie (\"Last Argument of Kings\")"},
{"id":"77","description":"We should forgive our enemies, but not before they are hanged.","category":"Bold","recipient":"Others","source":"Joe Abercrombie, Before They Are Hanged"},
{"id":"78","description":"But some things have to be done. It's better to do them, than to live with the fear of them.","category":"Heartening","recipient":"Others","source":"Joe Abercrombie (\"The First Law Trilogy\")"},
{"id":"79","description":"Let your plans be dark and as impenetrable as night, and when you move, fall like a thunderbolt.","category":"Bold","recipient":"Others","source":"Sun Tzu (\"Art of War\")"},
{"id":"80","description":"If you know the enemy and know yourself you need not fear the results of a hundred battles.","category":"Heartening","recipient":"Others","source":"Sun Tzu (\"Art of War\")"},
{"id":"81","description":"Someday, someone will best me. But it won't be today, and it won't be you.","category":"Heartening","recipient":"Self","source":""},
{"id":"82","description":"They've got us surrounded. The poor bastards","category":"Bold","recipient":"Others","source":""},
{"id":"83","description":"You can try to run and live another day. You can hope and pray that death won't take you on his way. You looked upon me and sealed your fate. But try and run for the hunt will be so fun, but you will only die tired at the end. Death comes for you today.","category":"Bold","recipient":"Self","source":""}
];